services:
  postgresql:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ainbidev
      POSTGRES_PASSWORD: 4!nb1deV
    volumes:
      - postgre_sql:/var/lib/postgresql/data
    networks:
      - portainer_network_public      
    ports:
      - 5432:5432

  pgadmin:    
    image: dpage/pgadmin4:9.1
    environment:
      PGADMIN_DEFAULT_EMAIL: ainbidev@proton.me
      PGADMIN_DEFAULT_PASSWORD: 4!nb1deV
      PGADMIN_LISTEN_PORT: 4000
    volumes:
      - postgre_sql_pgadmin:/var/lib/pgadmin
    networks:
      - portainer_network_public
    ports:
      - 4000:4000

volumes:
  postgre_sql:
  postgre_sql_pgadmin:

networks:
  portainer_network_public:
    external: true
    name: portainer_network_public