services:
  mariadb_mirror_vtiger:
    image: mariadb:11.4    # Same version of vtiger cpanel UK  
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vtiger-root    # root password for MariaDB (for testing use)
      MYSQL_DATABASE: vtiger            # initial database name (optional)
      MYSQL_USER: vtiger                # non-root user (optional)
      MYSQL_PASSWORD: vtiger            # password for vtiger user
    volumes:
      - mariadb_mirror_vtiger:/var/lib/mysql          # persistent storage for database data
    configs:
      - source: mariadb_conf
        target: /etc/mysql/conf.d/vtiger.cnf
    networks:
      - network_public
    deploy:
      placement:
        constraints:
          - node.role == manager          
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M      

configs:
  mariadb_conf:
    file: ./mariadb_vtiger.cnf

networks:
  network_public:
    external: true

volumes:
  vtiger_data:
  db_data:      