version: "3.7"

services:
  traefik:
    image: traefik:2.11.2
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=network_public"
      
      # HTTP and HTTPS entry points
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      # Added TCP entry point for PostgreSQL
      - "--entrypoints.postgres-tcp.address=:5432"

      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=ainbidev@proton.me"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"

      # Logging configuration
      - "--log.level=INFO"  # Changed from DEBUG to INFO for production use
      - "--log.format=common"  
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Catch-all HTTP redirection to HTTPS
        - "traefik.enable=true"
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-https@docker"
        - "traefik.http.routers.http-catchall.priority=1"

    volumes:
      # Docker socket (read-only for security)
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      # Certificates volume (ensure external volume exists)
      - "vol_certificates:/etc/traefik/letsencrypt"

    ports:
      # Expose HTTP and HTTPS ports directly on the host
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

      # Expose PostgreSQL TCP port directly on the host
      - target: 5432
        published: 5432
        mode: host

    networks:
      # Attach Traefik to the public network
      - network_public

volumes:
  vol_certificates:
    external: true
    name: volume_swarm_certificates

networks:
  network_public:
    external: true
    name: network_public
