services:
  registry:
    image: registry:2           # upstream Distribution project
    restart: unless-stopped
    volumes:
      - regdata:/var/lib/registry
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager      
      # ports:
      #   - 5000:5000 only inside the vps; no need to expose on the internet
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  buildkitd:
    image: moby/buildkit:rootless
    command:
      - --addr
      - tcp://0.0.0.0:1234
    ports: ["1234:1234"]
    volumes:
      - buildkit-cache:/var/lib/buildkit   # rootless data dir
    networks: [network_public]
    cap_add:                               # only what rootless needs
      - CAP_SYS_CHOWN
      - CAP_SETFCAP
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    deploy:
      placement:
        constraints: [node.role == manager]  

volumes:
  regdata:
  buildkit-cache:

networks:
  network_public:
    external: true

