services:
  vtiger_db_bkp:
    image: tiredofit/db-backup:latest
    restart: unless-stopped
    environment:
      # Connection
      - DB_TYPE=mysql
      - DB_HOST=31.22.4.11 # sv11.byethost11.org      
      - DB_NAME=purifika_u194194_2
      - DB_USER=purifika_pfk
      - DB_PASS=@PFK2025
      - DB_PORT=3306      
      - DB_GZ_RSYNCABLE=TRUE             # Use --rsyncable (gzip only) for faster rsync transfers and incremental backup deduplication.
      - DB_RESOURCE_OPTIMIZED=FALSE      # Perform operations at a lower priority to the CPU and IO scheduler
      - DB_CLEANUP_TIME=FALSE            # Value in minutes to delete old backups (only fired when backup interval executes)3
      - DB_BACKUP_LOCATION=FILESYSTEM    # Store backups on the local filesystem
      - DB_FILESYSTEM_PATH=/backup/vtiger
      - DEFAULT_COMPRESSION=BZ2
      - TZ=America/Sao_Paulo
      - DEFAULT_BACKUP_BEGIN="00 00 * * *" # 00 = 00:00 midnight  
      - DEFAULT_BACKUP_INTERVAL=1440    # 1440 minutes = 24 hours
      # Blackout period - backups are not allowed between 8:45am and 9:00am
      - DEFAULT_BACKUP_BLACKOUT_BEGIN="0545"    # 5 hours and 45 minutes
      - DEFAULT_BACKUP_BLACKOUT_END="2100"           # 9 hours pm
      # retention period for backups in minutes.
      - DEFAULT_CLEANUP_TIME=10080    #  7 days

    networks:
      - network_public      
    volumes:
      - type: bind
        source: /root/db_backups # must be created at vps before running this compose
        target: /backup
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager          
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M      

networks:
  network_public:
    external: true
    name: network_public