services:
  base: &base
    image: chatwoot/chatwoot:v4.0.2-ce
    env_file: .env ## Change this file for customized env variables
    volumes:
      - /data/storage:/app/storage
    networks:
      - chatwoot-net    

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - chatwoot-net    
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
    networks:
      - chatwoot-net        

  postgres:
    container_name: postgres-chatwoot
    image: pgvector/pgvector:pg17
    restart: always
    networks:
      - chatwoot-net        
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres      
      - POSTGRES_PASSWORD=chatwoot
    expose: # for clarity only accessible internally exposed, on this docker network
      - 5432

  redis:
    container_name: redis-chatwoot
    image: redis:alpine
    restart: always
    networks:
      - chatwoot-net    
    command: ["sh", "-c", "redis-server --port 6379"]
    env_file: .env
    volumes:
      - /data/redis:/data
    expose:
      - 6379


networks:
  chatwoot-net:
    driver: bridge